name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: true  # Clona anche i submoduli

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mpi-default-bin mpi-default-dev
      shell: bash

    - name: Update Submodules
      run: |
        git submodule update --init --recursive
      shell: bash

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build
      
    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3

    - name: Build Singularity Container
      run: singularity build --fakeroot singularity/cont.sif singularity/container.def
    
    - name: execute 
      run: singularity exec singularity/cont.sif /home/repo/build/main

